### ISSUE TITLE
[1.12] Startup crash

### ISSUE THREAD

**Issue by Blatts12** [Furgl/Stupid-Things#6]
https://pastebin.com/BQ0YWG9f

**Comment by Furgl** [comment]
This crash was caused by Forge being unable to find Acid's registration name while trying to get a filled bucket to add to the creative tab. This should never normally happen, so I would assume it is caused by one of the other mods you have installed interfering with fluid registration. 

To avoid this, you can disable Acid in the config, which will stop the code from attempting to add the filled bucket to the creative tab. Otherwise, you can try this version that just doesn't add a filled bucket of Acid to the creative tab: 
[Stupid Things-1.12-1.1.3-Acid-Fix.jar.zip](https://github.com/Furgl/Stupid-Things/files/1223773/Stupid.Things-1.12-1.1.3-Acid-Fix.jar.zip)

Let me know if this doesn't help and I will reopen the issue.

**Comment by 4karion** [comment]
Hi, I'm having the same (or a similar) issue. I've tried the "Acid-Fix" version but it still crashes. I'm using Twitch app.

Here's my crash:
https://pastebin.com/ytnk0Dza
